<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_db_object">
    <sys_db_object action="INSERT_OR_UPDATE">
        <access>public</access>
        <actions_access>false</actions_access>
        <alter_access>false</alter_access>
        <client_scripts_access>false</client_scripts_access>
        <configuration_access>false</configuration_access>
        <create_access>false</create_access>
        <create_access_controls>true</create_access_controls>
        <delete_access>false</delete_access>
        <extension_model/>
        <is_extendable>false</is_extendable>
        <label>Sample Exception</label>
        <live_feed_enabled>false</live_feed_enabled>
        <name>x_354377_exception_sample_exception</name>
        <number_ref/>
        <provider_class/>
        <read_access>true</read_access>
        <super_class/>
        <sys_class_code/>
        <sys_class_name>sys_db_object</sys_class_name>
        <sys_class_path/>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2019-06-25 08:32:32</sys_created_on>
        <sys_id>f1b83e70db1a7700f15d5c7a48961941</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>Sample Exception</sys_name>
        <sys_package display_value="Exception" source="x_354377_exception">baa83630db1a7700f15d5c7a48961994</sys_package>
        <sys_policy/>
        <sys_scope display_value="Exception">baa83630db1a7700f15d5c7a48961994</sys_scope>
        <sys_update_name>sys_db_object_f1b83e70db1a7700f15d5c7a48961941</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2019-06-25 08:32:32</sys_updated_on>
        <update_access>false</update_access>
        <user_role display_value="x_354377_exception.sample_exception_user" name="x_354377_exception.sample_exception_user">5309fe70db1a7700f15d5c7a48961997</user_role>
        <ws_access>true</ws_access>
    </sys_db_object>
</record_update>
